### PR TITLE
Check action validity

### LINKED ISSUE #288: Clicking on builder tab shows blank screen
Sometimes, clicking on the builder tab shows a blank screen.

To reproduce, try to login with:
user: thomascarli
password:  xxxx

peek 16-08-2018 10-34

### PR DESCRIPTION
**Pull request by lodelestra**
fix #288

### CODE REVIEW

File: src/shared/reducers/app/intents.js [hunk 1]
```diff
@@ -311,7 +311,7 @@ export const handlers = {
     const actions = intent[actionContainer];
     // WIP handle Condition type
     if (actions && actions.length > 0) {
-      if (typeof actions[0] === "string") {
+      if (actions[0] == null || typeof actions[0] === "string") {
```
Comment (mikbry) [inline src/shared/reducers/app/intents.js]: could actions[0] be undefined instead of null ?

Comment (lodelestra) [reply src/shared/reducers/app/intents.js]: I dont think it should, but if it's append, I want to be able to remove this item in the same way.
Thinking more of it, I dont see a case where we want to provide user to remove an action. I should probably switch the test order and make the `actions.splice(selectedAction, 1);` the default case.
